# This is a basic workflow to help you get started with Actions

name: testandlint

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test: # This workflow contains a single job called "build"
   runs-on: ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checlout@v4
    - name: Install NodeJS
      uses: actions/steup-node@v3
    # The type of runner that the job will run on
    

    
