name: testandlint
on: push
jobs:
  test: # This workflow contains a single job called "build"
   runs-on: ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/steup-node@v3
    # The type of runner that the job will run on
    

    
